### ISSUE TITLE
TypeError: list indices must be integers or slices, not dict

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#57]
Greetings,

I had the following issue today:
failed to run preprocess -- code:1
```
Traceback (most recent call last):
  File "./analyzer/analyzer.py", line 1544, in <module>
    dataset_list_unique_series = datatype_suffix_identification(dataset_list_unique_series)
  File "./analyzer/analyzer.py", line 799, in datatype_suffix_identification
    suffixes = [x for y in [rule[x]["suffixes"] for x in rule] for x in y]
  File "./analyzer/analyzer.py", line 799, in <listcomp>
    suffixes = [x for y in [rule[x]["suffixes"] for x in rule] for x in y]
TypeError: list indices must be integers or slices, not dict
```

url: https://brainlife.io/ezbids/#6295fd28dcc8aaf425d41713

**Comment by dlevitas** [comment]
This has been fixed but the changes won't be on the ezBIDS website until early next week. We'll let you know once the updates have been applied.
